### ISSUE TITLE
storing DynamicAvx2Searcher

### ISSUE THREAD

**Issue by daaku** [cloudflare/sliceslice-rs#54]
Until version `0.2` I could store `DynamicAvx2Searcher` pretty easily:

```rust
enum Matcher {
    Regex(Regex),
    String((String, DynamicAvx2Searcher)),
}
```

How do I do this in `0.3`? Apologies if this is a rust n00b question. I dynamically create many `Matcher`s and store them in a `Vec`.

**Comment by marmeladema** [comment]
Since version 0.3, `DynamicAvx2Searcher` has gained a generic type that describe the type of the needle but there is not default type for it so you need to choose.
Previously the needle was always heap allocated as a `Box<[u8]>` so you probably to change your enum to something like:
```
enum Matcher {
    Regex(Regex),
    String((String, DynamicAvx2Searcher<Box<[u8]>>)),
}
```

Additionally, please be aware that sliceslice is doing raw bytes substring search and is not utf8 aware.

**Comment by daaku** [comment]
Thank you for the super quick response. What type parameter to use wasn't something I understood, but I get it now!

**Comment by BurntSushi** [comment]
> Additionally, please be aware that sliceslice is doing raw bytes substring search and is not utf8 aware.

I believe the only semantic difference this impacts is matching an empty string. When searching a `&str`, a regex will return matches only at UTF-8 boundaries. So if you just make sure to use a regex for an empty string, then everything should work out!

**Comment by daaku** [comment]
Thanks for the heads up @BurntSushi! That would have been a bug in my current logic, which maybe you have thoughts on:

```rust
enum Matcher {
    Regex(Regex),
    String((String, DynamicAvx2Searcher<Box<[u8]>>)),
}

impl Matcher {
    fn new(s: &str) -> Result<Self> {
        let escaped = regex::escape(s);
        Ok(if escaped == s {
            Self::String((escaped, unsafe {
                DynamicAvx2Searcher::new(s.as_bytes().to_owned().into())
            }))
        } else {
            Self::Regex(Regex::new(s)?)
        })
    }

    fn is_match(&self, text: &str) -> bool {
        match self {
            Self::Regex(re) => re.is_match(text),
            Self::String((_, s)) => unsafe { s.search_in(text.as_bytes()) },
        }
    }

    fn as_str(&self) -> &str {
        match self {
            Self::Regex(re) => re.as_str(),
            Self::String((s, _)) => s.as_str(),
        }
    }
}
```

**Comment by BurntSushi** [comment]
@daaku From what I can tell, that code is unsound. Since `is_match` is a safe routine, it has the responsibility of guaranteeing that `s.search_in` is itself safe to call. The simplest way is to insert an `is_x86_feature_detected!` call in the `new` constructor, and only build the `Self::String` variant when the `avx2` feature is enabled.

As for your `escape` trick to detect if the regex is a literal, I can't immediately think of anyway that could give false positive results.

Also note that `Regex` will do literal matches like this for you automatically. But it's latency (visible when searching short haystacks) will likely be worse than your code.

**Comment by daaku** [comment]
Thanks, appreciate the code review! I'll add the `is_x86_feature_detected` to ensure `avx2` is enabled. My original implementation used `Regex` alone, but profiling found it to be a bottleneck which is how I ended up finding this crate after first just doing the std library substring search. I recently made a branch with your new `memchr::memmem::find` implementation, but haven't had a chance to properly compare it yet!

**Comment by marmeladema** [comment]
> I believe the only semantic difference this impacts is matching an empty string. When searching a &str, a regex will return matches only at UTF-8 boundaries. So if you just make sure to use a regex for an empty string, then everything should work out!

@BurntSushi `DynamicAvx2Searcher` will always return `true` when searching for an empty needle. Doesn't that solve the problem you were thinking about?

**Comment by BurntSushi** [comment]
@marmeladema Oh right right. I forgot it was a binary match and that this crate doesn't return the match location. So yes, you are correct, UTF-8 should be irrelevant. :-)
